# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-10 01:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landinator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookAdCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='codigo numerico del anuncio creado en facebook', max_length=30, verbose_name='Identificador de Anuncio')),
            ],
        ),
        migrations.AddField(
            model_name='formulariodinamico',
            name='facebook_ad_code_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landinator.FacebookAdCode'),
        ),
    ]
