# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-10 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landinator', '0002_auto_20170109_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulariodinamico',
            name='facebook_ad_code_list',
        ),
        migrations.AddField(
            model_name='formulariodinamico',
            name='facebook_ad_code_list',
            field=models.ManyToManyField(to='landinator.FacebookAdCode'),
        ),
    ]
