# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-01 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landinator', '0004_auto_20170109_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulariodinamico',
            name='facebook_ad_code_list',
        ),
        migrations.AddField(
            model_name='facebookadcode',
            name='formulario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landinator.FormularioDinamico'),
        ),
    ]
