# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-02 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landinator', '0005_auto_20170201_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookFanPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Fan Page')),
                ('fan_page_id', models.CharField(max_length=100, verbose_name='ID de la Fan Page')),
                ('token', models.CharField(max_length=100, verbose_name='Token de la Fan Page')),
            ],
        ),
    ]
