# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-02 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landinator', '0006_auto_20170202_2044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facebookfanpage',
            options={'verbose_name': '06 Fan Page', 'verbose_name_plural': '01 Fan Pages'},
        ),
    ]
